### ISSUE TITLE
Stopping tor

### ISSUE THREAD

**Issue by andrasnagya** [datawookie/medusa-proxy#2]
Hi,

First of all, thank you for your work!
I just started to use your tool and encountered a strange problem.
```

[   INFO] Stopping tor (port 10012).
Exception ignored in: <function Service.__del__ at 0x753417142660>
Traceback (most recent call last):
  File "/proxy/service.py", line 21, in __del__
  File "/proxy/service.py", line 52, in stop
  File "/proxy/service.py", line 41, in kill
  File "/proxy/service.py", line 33, in pid
NameError: name 'open' is not defined
```

I will try to:
- make this error reproducible, to understand how it happens
- try to fix it
- submit a pull request to make this project more robust

If you have any comment that might can help please let me know.
Thank you again for this tool!

**Comment by andrasnagya** [comment]
@datawookie Thank you!
I am testing it for a while and it seems you have resolved this issue 
I made a fork and come to the same conclusion: its better for that open statement to be in a context manager.

You can close this one.
Thank you for your update!

**Comment by andrasnagya** [comment]
By the way.
I have read your wonderful [blog post](https://datawookie.dev/blog/2021/10/medusa-multi-headed-tor-proxy/).
You described this tool is especially well paired with [scrapy-rotating-proxies](https://github.com/TeamHG-Memex/scrapy-rotating-proxies) package.

At the moment I am using this with poor man's rotating proxy.:
If someone have only a moderate amount of url-s (10K-200K) and don't want to config scrapy this pattern might be a good substitute for them. 


`def get_proxy_list():
    proxy_list_url = "http://tor-proxy-rotating:8800/"
    response = requests.get(proxy_list_url)
    proxy_list = response.text.splitlines()
    modified_url_list = [url.replace('127.0.0.1', 'tor-proxy-rotating') for url in proxy_list]

    return modified_url_list`
    
`def get_proxy_cycle():
    proxy_list = get_proxy_list()
    proxy_cycle = itertools.cycle(proxy_list)
    return proxy_cycle`
    
    
    I have also wrote a little script to start the docker container with a bit more dynamically configured ports.
    If you are open for contribution I can share it on my fork and add a pull request. 
    
    Kind regards
